#!/bin/bash


if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=0000
fi

specs=""
for spec in `git diff --cached --name-status | awk '$1 != "R" { print $2 }' | grep "\.rb$" | sed 's/^app/spec/g' | sed 's/\.rb/_spec.rb/g'` ; do
  test -f $spec && specs="$specs $spec"
done

test -z "$specs" && exit 0
echo "Found specs $specs please be patient..."
grep zeus Gemfile >/dev/null 2>&1 && ( zeus spec $specs || exit 1 )
grep spork Gemfile >/dev/null 2>&1 && ( rspec $specs || exit 1 )
if [ ! $? -eq 0 ] ; then
  echo "Some specs had failed"
  exit 1
fi
exit 0
